ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDSzCCAjOgAwIBAgIQTLXooqXJcb7M60pRgzJ+vjANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjMxMDE4MDkxNTUxWhcNMzMx
  MDE1MDkxNTUxWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
  SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCdcJ7+a335LF55n3Pt+KSZcWN8cVzlLj33
  tr+7qb2gQeIbNk4uOcrMwxBN9JE99oSyZD6CTyMJzpwyG787y+rw2mMG+PXDDpaZ
  1yR6+FhK5KWPDXWdKvMKpFx2eeUV/JunZM9YZrCdVtD94FghjQ8EcHEecgMvWld9
  ZrVkCho/kcwU5hL2NBf+Ax0zcDmf6UDU7k9VKo6MbFLqmp3MPv30nl9cpqF1kO6m
  jTRvbT+daKJxMo2puOQKwHnKqOckbEYVGxCwSE7ZspZMDqQ2oEX9NhWbCxl8AW0q
  2z2T6jjtmZwt/34VJm/hAUpohW0Sv+eai06613yYXsqxEKqqS9f9AgMBAAGjgYww
  gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
  AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTGpcoaPwlpVcHhFupoxGFxiRFK
  jDAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
  hkiG9w0BAQsFAAOCAQEAecvuUx3qyKZIl7P1NXvRO7AI+LL12/jqQUcCOnXLLu9L
  Khpi4HjRxx5ASd/aVjfrI/R/TCHkVYFmR2FRte7JYaFbuFp3eGL/H4yL9GAcb5Fl
  kAB12d15eRKXXeTQTLWXPvmwtFrFUWenIJOVd4If/ERG1TruL0wLJYmEBaFV8P1/
  AxEs3wqKriMrGYfB1ztD8MOmeLsdh5UqXeAri1Bj2wAPHhL8/IwfHmtgvUlETgUl
  Xvp6ktXIkqFiXAHszacH3ZV6eJ8t3RxybOfONR1mROtH/riKv3z65TDaUzhX5/h7
  HtcJetOeI0ep8RhfyWIT/YSIj3r8BzuaQ+2iuGuT6Q==
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDOzCCAiOgAwIBAgIQPImTzS7lfIi877Chyl+L6TANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjMxMDIzMDc1MjA2WhcNMjQx
  MDIyMDc1MjA2WjAmMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxDTALBgNVBAMTBHNv
  YXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC84QAfnklS/1efhFY1
  DNtVElVwqdbiiNIHZNoe4t3HPfIhQmSaWmJvnz2q78Rcu5ZX2snCAB7oee8N/6lv
  m1VmQc9561uBy7oGXez8DLEMxEmkekQTJOLx+BzXHrwyxGUzU2HJ75Gna2lL47x3
  lKfTkiOq3IZ0uCJSzA+1soiaYSs8NaAdQEmEExhEqsLkt/kGNPZOjz4GRSn8q9OL
  4CJrFSLXbCAq4iIBX+wP0++ftBhQkEdSEuHDDvAfxALko20rKqVFxJPmvoL3urnv
  rTkloS9VwzOKlCmM+sNYdwFyzRuhOPrp6a+ISiR6RW5+GzlkN8Lj20Gc6891UN0W
  KtSvAgMBAAGjcTBvMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcD
  AQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBTGpcoaPwlpVcHh
  FupoxGFxiRFKjDAPBgNVHREECDAGggRzb2FyMA0GCSqGSIb3DQEBCwUAA4IBAQB7
  E4C4KG1jeYmCACYkzS2PJfs3XvJrei9ipTpwplClimQxAftDMyKOPlrOrkOTlkTh
  vz7H2XNaYdXTHxQZo3b8hY/3PW9jnvLZCpQ55QQc7sPq5mEkwCjFMaFvJVp2YPfq
  3dNEgC2e/8+TtIb8SxsdbauA6quE1gDJbo8AcAwC+9vNvn/VEXapXHp3URpwYHIw
  ssUmB/X/MFbBapB6hJwL0HQgyUWB6gDEDgLOC3ZHtAbgJQ8W2kz8GX3mEcfcfiD9
  pupxUP9Pe6coTYmc/g102eCJHBruZPOxJ1mIfna5dcAGi24BgcXBneoq2NaJ4BG/
  H8Jrxy1ghAWOqiI2rAFz
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAvOEAH55JUv9Xn4RWNQzbVRJVcKnW4ojSB2TaHuLdxz3yIUJk
  mlpib589qu/EXLuWV9rJwgAe6HnvDf+pb5tVZkHPeetbgcu6Bl3s/AyxDMRJpHpE
  EyTi8fgc1x68MsRlM1Nhye+Rp2tpS+O8d5Sn05IjqtyGdLgiUswPtbKImmErPDWg
  HUBJhBMYRKrC5Lf5BjT2To8+BkUp/KvTi+AiaxUi12wgKuIiAV/sD9Pvn7QYUJBH
  UhLhww7wH8QC5KNtKyqlRcST5r6C97q57605JaEvVcMzipQpjPrDWHcBcs0boTj6
  6emviEokekVufhs5ZDfC49tBnOvPdVDdFirUrwIDAQABAoIBAAVzLJC8/XqimYGl
  zOL8+vsqa0Kz89pXfk/uTgjkHOgZ1nm1M7fscbiszJe5EV5nnz/rtTSe0kV89zPd
  M6NfxQgNUBJBg0NsgHKclTD0oMswgrt3N62hu9alhReD8IQ6fH0No92yxu4gwEoL
  SS3eITWOmu7cLBkEEyF2d+GTRDPIGz5Yfc0JNsPFMkjTp+jA+VYIJ9zMs8ROr7yU
  QZ9cLAK+iaOWAd8PsAyN1YEZs/OtDqgLioMPTFYx6huBIzAtPUQFeChydi0uS2w8
  5bWN08WJ2C184qihBqT6MUBV1xEfJ73ZB/HAAnr0yjQdgjsf6xXqQtymw5oXNfF3
  5HY/jYkCgYEA7wv7p5Hj2UkVHlIi0YCbZEt0Zi4hkwvYRKIPRjP3jAHxYAurfaDU
  5tenv2s/BR3e5NDiV9EKibyQPNnXU0ep3GjyC1OnhneWvOK2AZQBQMHLr/5+0FQZ
  Qgf/lYyLazEd2xoZSBSmJJI9vO1dey+B0FgSsjPViDQs9IAN6ChovPsCgYEAykYx
  jr4gONzo2ZbAs70SJQqxr4paXhUIkyS7ZBrhf2hjeNzbpgzAUkenYS2xEU8zPnNV
  UqekHEHBq+fwYf++Nb/R9eD40nUvAKD0wLDAgO/d7eZabzEbj6ibkiz5V0+ZNDVA
  N6sq33ESEZkhCHnDwVYmUFO+wHfu6PII45TQEN0CgYBPKXG6KWcCAuC6fMrJBETx
  bsdqOyalMov5Fo3mWrlEpTQQ8WxmGwfGNm53xoVFJYI11jLOkAxkVoyRijZzfszy
  j9JwC9Dzh9DkVlOdrCzKDCNu8eF/DgqbQljSZouZANf5QehTZXsrqz5EvXpym+Xq
  X/A5EU9KXrTwdyOj2RXuVwKBgDR/94jnDBH2NHGVUTrVjgoTNn8rV70nlGwskn6v
  A2xAOeE64b+9e4Vfl6//Xf/yIIjLApBLdqrm3k+yCZBGAqaMvQAmfi6Rv7tYC26f
  8bcFiwKeUUae5lppFsff6G+i9063q41HXf9Up63tosdCY26g35zlv5LRDi9j8q6v
  Bzn5AoGBAO4b49f89J22m+f2GmzPjFTrUL1KHVoprXdCdj6cVQUcpuKqTpyf6owa
  JVqSQLPZA34LmF25njAPQ4ATeIzqRmWds8nolK6nClT7AA7jUiKMgrZyrDyu3gkr
  g0MQuxANvqc9PPXtNpH2ZaTOo+emNWs2BDPCB/f3KUO6ECG4upMi
  -----END RSA PRIVATE KEY-----
api_connection_string: 0.0.0.0:8001
name: soar
